### PR TITLE
Change shebang to /usr/bin/env python

### PR DESCRIPTION
**Pull request by rata**
This makes it possible to run the s3redirects.py file directly inside a python
virtualenv.

### CODE REVIEW

**Comment by nathangrigg** [comment]
If you install to your virtualenv with pip or easy_install, it will take care of the shebang for you. This is more reliable than using `env` because it doesn't depend on your PATH variable (i.e. whether the virtualenv is "active")

**Comment by rata** [comment]
On Tue, Apr 15, 2014 at 06:29:54PM -0700, Nathan Grigg wrote:

> If you install to your virtualenv with pip or easy_install, it will take care
> of the shebang for you. This is more reliable than using env because it doesn't
> depend on your PATH variable (i.e. whether the virtualenv is "active")

Yeap, but I was doing some small changes and trying some things, so installing
with pip/easy install was disturbing.

Also, note that changing the shebang shouldn't break anything and also I think
/usr/bin/env is recommended since a few years already, so I don't see any
downside with this small change.

Am I missing something ?

Thanks,
Rodrigo

**Comment by nathangrigg** [comment]
You are right that this won't break anything. The reason I'm hesitant is that changes to accommodate one person's development process usually aren't worth sending back.

You are also, however, right that /usr/bin/env is more universal and may solve problems for more than just you, so I'll merge.

**Comment by rata** [comment]
Thanks! :)

**Pull request merged**
